---
- hosts: [os_controllers]
  vars_files:
    - ./vars/os-variables.yml
  tasks:
    - name: "Install dashboard"
      apt: name=openstack-dashboard update_cache=yes state=latest

    - name: "Remove ubuntu theme"
      apt: name=openstack-dashboard-ubuntu-theme state=absent

    - name: "copy config file"
      template: src=./templates/local_settings.py.j2
            dest=/etc/openstack-dashboard/local_settings.py
            owner=root
            group=root
            mode=0644

    - name: "reload apache2"
      service: name=apache2 state=reloaded
